---
Name: mysite
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SilverStripe\View\SSViewer:
  themes:
    - 'base'
    - '$default'
SilverStripe\GraphQL\Controller:
  schema:
    scaffolding:
      types:
        Item:
          fields: '*'
          operations:
            read: true